version: "3.9"

services:
  database:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
        - database_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=test_password
        - POSTGRES_USER=test_user
        - POSTGRES_DB=main
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=redis_test
      - REDIS_PORT=6379
      - REDIS_DATABASES=6
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - FLOWER_UNAUTHENTICATED_API=true
      - FLOWER_PORT=5555
    volumes:
      - flower_data:/data
    ports:
      - "5555:5555"

volumes:
  database_data:
    driver: local
  redis:
    driver: local
  flower_data:
    driver: local