"""init website

Revision ID: b7f8dc3cdd53
Revises: 
Create Date: 2024-01-03 02:46:20.341018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f8dc3cdd53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('robots_txt', sa.String(), nullable=True),
    sa.Column('sitemap', sa.String(), nullable=True),
    sa.Column('disallow', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='document'
    )
    op.create_index(op.f('ix_document_website_id'), 'website', ['id'], unique=False, schema='document')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_website_id'), table_name='website', schema='document')
    op.drop_table('website', schema='document')
    # ### end Alembic commands ###
